# -*- coding: utf-8 -*-
"""Residual1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBHHthI2JPJ-Bz7qXhZV2ig9DEfpSKFj
"""

#1st code
import numpy as np
import matplotlib.pyplot as plt
def defocus_zernike(r,theta,a):
  return (2*r**2-1)*a
a=5.7
a1=np.linspace(4,8,50)
a_new = np.array(a1)
Res = np.abs(a_new - a)
#plt.plot(a1, Res, marker='.')
plt.scatter(a1,Res, marker = '.')
plt.xlabel("Zernike Coeff(defocus)")
plt.ylabel("Residuals")
plt.title(" Defocus ")

#2nd code
import numpy as np
import matplotlib.pyplot as plt

a1_vals = np.linspace(4, 8, 10)
a2_vals = np.linspace(4, 8, 10)
a3_vals = np.linspace(4, 8, 10)

a1_t = 4.8
a2_t = 5.8
a3_t = 6.8

Res = []

for a1 in a1_vals:
    for a2 in a2_vals:
        for a3 in a3_vals:
            res = abs(a1 - a1_t) + abs(a2 - a2_t) + abs(a3 - a3_t)
            Res.append(res)

Res = np.array(Res)

# iterations
iteration = np.arange(len(Res))

plt.scatter(iteration, Res,s=2, marker='.')
plt.xlabel("Iteration")
plt.ylabel("Residual (Coefficient Difference)")
plt.title("Iteration vs Residual(Def,Astigx,Astigy)")
plt.show()

#3rd code
import numpy as np
import matplotlib.pyplot as plt
def Zernike(r, theta, a1, a2, a3):
    return (a1 * (2*r**2 - 1) +
            a2 * r**2 * np.cos(2*theta) +
            a3 * r**2 * np.sin(2*theta))

r_val = 1.0
theta_val = 0.0

a1_coeffs = np.linspace(4, 8, 10)
a2_coeffs = np.linspace(4, 8, 10)
a3_coeffs = np.linspace(4, 8, 10)

Zernike_values = []
for a1 in a1_coeffs:
    for a2 in a2_coeffs:
        for a3 in a3_coeffs:
            val = Zernike(r_val, theta_val, a1, a2, a3)
            Zernike_values.append(val)

Zernike_values = np.array(Zernike_values)

a1_t = 4.8
a2_t = 5.8
a3_t = 6.8

target = Zernike(r_val, theta_val, a1_t, a2_t, a3_t)

Res = np.abs(Zernike_values - target)

iteration = np.arange(len(Res))
plt.scatter(iteration, Res, s= 2, marker='.')
plt.xlabel("Iteration")
plt.ylabel("Residual")
plt.title("Iteration vs Residual (Zernike-Based)")
plt.grid(True)
plt.show()

#4th code
import numpy as np
import matplotlib.pyplot as plt
N = 256
x = np.linspace(-1, 1, N)
y = np.linspace(-1, 1, N)
X, Y = np.meshgrid(x, y)
r = np.sqrt(X**2 + Y**2)
theta = np.arctan2(Y, X)
mask = r <= 1

def Wavefront(a1, a2, a3):
    return (a1*(2*r**2 - 1) +
            a2*r**2*np.cos(2*theta) +
            a3*r**2*np.sin(2*theta))

def PSF(a1, a2, a3):
    W = Wavefront(a1, a2, a3)
    phase = 2*np.pi * W * mask
    P = mask * np.exp(1j * phase)
    PSF = np.abs(np.fft.fftshift(np.fft.fft2(P)))**2
    return PSF / PSF.max()

a1_t = 4.8
a2_t = 5.8
a3_t = 6.8

PSF_target = PSF(a1_t, a2_t, a3_t)

a1_vals = np.linspace(4, 8, 10)
a2_vals = np.linspace(4, 8, 10)
a3_vals = np.linspace(4, 8, 10)

residuals = []

for a1 in a1_vals:
    for a2 in a2_vals:
        for a3 in a3_vals:
            psf_new = PSF(a1, a2, a3)


            res = np.sum(np.abs(psf_new - PSF_target))
            residuals.append(res)

residuals = np.array(residuals)
iterations = np.arange(len(residuals))

plt.figure(figsize=(7,4))
plt.scatter(iterations, residuals, s=2)
plt.xlabel("Iteration")
plt.ylabel("Residual (PSF difference)")
plt.title("Iteration vs PSF Residual")
plt.grid(True)
plt.show()